### ISSUE TITLE
Clean up and document repo

### ISSUE THREAD

**Issue by takluyver** [WRSC/scoring#1]
- [x] Tag current state so we have a record of what was used for 2018 contest
- [x] Move the scripts out of their folders, as we've ended up with one file per folder
- [x] Add a README explaining what this is and how to use the scripts
- [x] Docstrings, comments and general clarification inside the scripts

**Comment by takluyver** [comment]
I've made a tag `wrsc2018` as a synonym to `v1.0`. We're not really doing releases here - at least, I wasn't planning to - so I think it's more useful to name the tag for the competition that code was used at.

**Comment by takluyver** [comment]
I've made a start on cleaning these scripts up and making them clearer.

- [x] More clarification of analyse_station_keeping, the most complex script
- [ ] Is it worth using numpy arrays for the coordinates? This makes it simpler to do maths with them, but I'm not sure how big a difference it makes overall.

**Comment by takluyver** [comment]
OK, I'm happy with this now.

I decided not to convert the coordinate maths to numpy throughout, but I did use it to simplify the code for finding the average of points for station keeping.

**Comment by Nanoseb** [comment]
So sorry for not helping you on this. It's never nice to clean up other's people code.

**Comment by takluyver** [comment]
That's OK - the code was fairly easy to follow, and there wasn't all that much of it.
